Base scripts
ostis-ai/ostis-scripts pull request #1
Opened 2024-03-27 12:45 UTC by NikitaZotov

2024-03-27 16:37 UTC, MksmOrlov requested changes
Add readme and scripts documentation

2024-03-27 17:00 UTC, MksmOrlov commented on submodule-scripts/update_submodule.sh
> +    ;;
what is the difference?

2024-03-29 10:26 UTC, FallenChromium commented
I don't see much value in these scripts, since it's not a standard (nor a guarantee) that all our projects use CMake as one and only step for building the project, or that submodules are only installed using `git submodule`. 

Those choices are not always the optimal solution, but the existence of this repo will push people into using this solution rather than what's optimal for the project they're building. Any change to these scripts may break behavior expectations (or customizations and crutches that were made around those expectations, because clearly the scripts in the PR are not extensible enough to cover all the cases). It's applicable vice versa as well - a small change to the project's requirements may make these scripts unusable for the tasks they're supposed to solve.

TL;DR it doesn't make sense to make these quite specific scripts a separate module since the logic of installing submodules and building the project is tightly coupled to the project - and making tightly coupled code modular leads to bugs, inconsistencies and ugly workarounds.

2024-03-29 10:27 UTC, FallenChromium requested changes
I don't think this repo should exist in a form that is suggested in this PR

2024-09-26 11:17 UTC, closed without merging